apiVersion: v1
kind: Service
metadata:
  name: mcs-bungee-cord-load-balancer
  labels:
    app: mcs-bungee-cord-load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: 25565
      targetPort: 25577
  selector:
    app: mcs-bungee-cord