apiVersion: v1
kind: PersistentVolume
metadata:
  name: mcs-world-1-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: 'F:\TUA\MinecraftServer\data\mcs-world-1'