server_connect_timeout: 5000
remote_ping_cache: -1
forge_support: false
player_limit: 1000
permissions:
  default:
    - bungeecord.command.server
    - bungeecord.command.list
  admin:
    - bungeecord.command.alert
    - bungeecord.command.end
    - bungeecord.command.ip
    - bungeecord.command.reload
timeout: 30000
log_commands: false
network_compression_threshold: 256
online_mode: false
disabled_commands:
servers:
  lobby:
    motd: 'Lobby server'
    address: lobby-service:25565
    restricted: false
  mcs-world-1:
    motd: 'World 1 server'
    address: mcs-world-1-service:25565
    restricted: false
listeners:
  - query_port: 25577
    motd: '&1Another Bungee server'
    tab_list: GLOBAL_PING
    query_enabled: false
    proxy_protocol: false
    forced_hosts:
      pvp.md-5.net: pvp
    ping_passthrough: false
    priorities:
      - lobby
    bind_local_address: false
    host: 0.0.0.0:25577
    max_players: 1000
    tab_size: 60
    force_default_server: true
ip_forward: true
remote_ping_timeout: 5000
prevent_proxy_connections: false
groups:
  md_5:
    - admin
connection_throttle: 4000
stats: c4b9cabb-93e9-4bce-93ab-4b18642e6f3e
connection_throttle_limit: 3
log_pings: true